language: generic

install:
    - sudo apt -y install libgtk2.0-dev

    - wget -t 10 -O lazarus-project_1.8.2-0_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.2/lazarus-project_1.8.2-0_amd64.deb/download
    - wget -t 10 -O fpc_3.0.4-2_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.2/fpc_3.0.4-2_amd64.deb/download
    - wget -t 10 -O fpc-src_3.0.4-2_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.2/fpc-src_3.0.4-2_amd64.deb/download
    - sudo dpkg -i fpc-src_3.0.4-2_amd64.deb fpc_3.0.4-2_amd64.deb lazarus-project_1.8.2-0_amd64.deb

script:
    - make
    - make build_tests
    - make test

notifications:
  slack:
    secure: PCe/rd18XEEH3Pq6ugftgz8+lqWn4XOGc6QbNcax5virYuWaYaEEq9Sq3K0HqdEYyLrWV8r3hcEcZd43zsHkeqIZKsT7ieQzaT2r9HoEGeU4xX7WJmj9rZUnpZuY7aD6qa6/1x5XgwDeBYEeKc87HWEuiJeo9NKOmYMtKvPwxzc=
