language: generic

addons:
  apt:
    update: true

install:
    - sudo apt-get update
    - sudo apt -y install libgtk2.0-dev
    - wget -t 10 -O lazarus-project_2.0.0RC2-0_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0RC2/lazarus-project_2.0.0RC2-0_amd64.deb/download
    - wget -t 10 -O fpc-laz_3.0.4-1_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0RC2/fpc-laz_3.0.4-1_amd64.deb/download
    - wget -t 10 -O fpc-src_3.0.4-2_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0RC2/fpc-src_3.0.4-2_amd64.deb/download
    - sudo dpkg -i fpc-src_3.0.4-2_amd64.deb fpc-laz_3.0.4-1_amd64.deb lazarus-project_2.0.0RC2-0_amd64.deb
    - sudo tar -vzxf x86_64-linux-prt0-pre2.26-binutils.tar.gz --overwrite --no-same-owner --no-same-permissions -C /usr/

script:
    - make
    - make test

notifications:
  slack:
    secure: PCe/rd18XEEH3Pq6ugftgz8+lqWn4XOGc6QbNcax5virYuWaYaEEq9Sq3K0HqdEYyLrWV8r3hcEcZd43zsHkeqIZKsT7ieQzaT2r9HoEGeU4xX7WJmj9rZUnpZuY7aD6qa6/1x5XgwDeBYEeKc87HWEuiJeo9NKOmYMtKvPwxzc=
