language: c

install:
    - sudo apt -y install libgtk2.0-dev
    - wget http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.6.4/lazarus-project_1.6.4-0_amd64.deb
    - wget http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.6.4/fpc-src_3.0.2-170225_amd64.deb
    - wget http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.6.4/fpc_3.0.2-170225_amd64.deb
    - sudo dpkg -i fpc-src_3.0.2-170225_amd64.deb fpc_3.0.2-170225_amd64.deb lazarus-project_1.6.4-0_amd64.deb

script:
    - make
    - make build_tests
    - make test
