language: c

install:
    - sudo add-apt-repository -y ppa:jonathonf/lazarus
    - sudo apt-get update
    - sudo apt-get -y install fpc lazarus
script:
    - make
    - make build_tests
    - make test
