dist: xenial

language: generic

addons:
  apt:
    update: true
    packages:
      - libgtk2.0-dev
      - libgl1-mesa-dev

before_install:
    - wget -t 10 -O lazarus-project_2.0.0RC3-0_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0RC3/lazarus-project_2.0.0RC3-0_amd64.deb/download
    - wget -t 10 -O fpc-laz_3.0.4-1_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0RC3/fpc-laz_3.0.4-1_amd64.deb/download
    - wget -t 10 -O fpc-src_3.0.4-2_amd64.deb https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0RC3/fpc-src_3.0.4-2_amd64.deb/download
    - sudo dpkg -i fpc-src_3.0.4-2_amd64.deb fpc-laz_3.0.4-1_amd64.deb lazarus-project_2.0.0RC3-0_amd64.deb

script:
    - make
    - make test

notifications:
  slack:
    secure: PCe/rd18XEEH3Pq6ugftgz8+lqWn4XOGc6QbNcax5virYuWaYaEEq9Sq3K0HqdEYyLrWV8r3hcEcZd43zsHkeqIZKsT7ieQzaT2r9HoEGeU4xX7WJmj9rZUnpZuY7aD6qa6/1x5XgwDeBYEeKc87HWEuiJeo9NKOmYMtKvPwxzc=
